name: fdl_bot
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
    pedantic: ^1.10.0
dependencies:
    dart_minecraft: ^0.4.0
    nyxx: ^2.1.2
    nyxx_interactions: ^2.0.3
